# -*- coding: utf-8 -*-
"""phase_portrait.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19KbCrU9BYKnfFASz9wJVIRHeTO8dN8QA
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
plt.rcParams['svg.fonttype'] = 'none'
font_params = {'font' : 'Arial', 'fontsize' : 12, 'fontweight' : 'bold'}

x,y = np.meshgrid(np.linspace(0, 2, 9),np.linspace(0, 2, 9))

dxdt = x * (0.7 - 0.5*y - 0.4*x)
dydt = y * (0.7 - 0.5*x - 0.4*y)
vnorm = np.hypot(dxdt,dydt)

# PHASE PORTRAIT WITH VEC MAGNITUDE INDICATED BY ARROW LENGTH
plt.figure(figsize=[4,4])
plt.quiver(x, y, dxdt, dydt)
plt.xticks(**font_params)
plt.yticks([0, 0.5, 1, 1.5, 2], **font_params)
plt.xlabel('x', **font_params)
plt.ylabel('y', rotation=0, **font_params)
plt.title('Phase Portrait', **font_params)
plt.savefig('portrait.svg')
plt.close()

# PHASE PORTRAIT WITH VEC MAGNITUDE INDICATED BY ARROW COLOR
plt.figure(figsize=[3,3])
plt.quiver(x, y, dxdt/vnorm, dydt/vnorm, vnorm, cmap='jet', clim=(vnorm.min(), vnorm.max()))
plt.xticks(fontsize=12, fontweight='bold')
plt.yticks([0, 0.5, 1, 1.5, 2], **font_params)
plt.xlabel('x', **font_params)
plt.ylabel('y', rotation=0, **font_params)
plt.title('Phase Portrait', **font_params)
plt.savefig('portrait_color.svg')
plt.close()

# COLOR BAR
plt.figure(figsize=[3,3])
norm = plt.Normalize(vmin=vnorm.min(), vmax=vnorm.max())
plt.colorbar(cm.ScalarMappable(norm=norm, cmap='jet'), label='Vector Magnitude')
plt.savefig('colorbar.svg')
plt.close()
